services:
  registration-database:
    image: mysql:9.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registration
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - registration_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
      interval: 5s
      timeout: 5s
      retries: 3

  catalog-database:
    image: mysql:9.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3308:3306"
    volumes:
      - catalog_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
      interval: 5s
      timeout: 5s
      retries: 3

  catalog-metadata-database:
    image: mongo:8.2
    ports:
      - "27018:27017"
    volumes:
      - metadata_data:/data/db
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3

  catalog-cache:
    image: redis:8.6
    ports:
      - "6380:6379"
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    networks:
      - redis-network
    depends_on:
      - catalog-cache

volumes:
    registration_data:
    catalog_data:
    metadata_data:
    redis-insight-data:

networks:
  redis-network:
    driver: bridge