spring:
  application:
    name: marketplace

  docker:
    compose:
      lifecycle-management: start-only

# REGISTRATION (MySQL 3307)
registration:
  datasource:
    url: jdbc:mysql://localhost:3307/registration
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# CATALOG (MySQL 3308)
catalog:
  datasource:
    url: jdbc:mysql://localhost:3308/catalog
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# CATALOG (CACHE)
  data:
    redis:
      client-type: jedis

# VIRTUAL-THREADS
  threads:
    virtual:
      enabled: true

management:
  endpoint:
    health:
      show-details: always

#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org.hibernate: DEBUG

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.schema: DEBUG
#
#    org.springframework.boot.autoconfigure: DEBUG
